version: '2'
services:
  mysql:
    image: "centos/mysql-56-centos7:latest"
    networks:
     - mysql-nw
    volumes:
     - ./db:/var/lib/data
     - ./db:/docker-entrypoint-initdb.d/
    environment:
     - MYSQL_ROOT_PASSWORD=password
    ports:
     - "3308:3306"

networks:
  mysql-nw:
    driver: bridge
