version: '2'
services:
  wildfly13:
    image: "jboss/wildfly:13.0.0.Final"
    networks:
     - wildfly13
    ports:
     - "80:80"
     - "8083:8080"
    volumes:
     - ./jboss-app:/var/lib/jboss-app
     - ./jboss-as:/var/lib/jboss-as
    entrypoint: /bin/bash -c "tail -f /dev/null"
    environment:
     - DEBUG=true

networks:
  wildfly13:
    driver: bridge
