version: '2'
services:
  mariadb:
    image: "centos/mariadb:latest"
    networks:
     - mariadb-nw
    volumes:
     - ./db:/var/lib/data
     - ./db:/docker-entrypoint-initdb.d/
    environment:
     - MYSQL_ROOT_PASSWORD=password
    ports:
     - "3307:3306"

networks:
  mariadb-nw:
    driver: bridge
